# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='alpha_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='alpha_lastupdate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='beta_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='beta_lastupdate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='domain_prefix',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
