# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_auto_20160709_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='alpha_lastupdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='beta_lastupdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
