# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_auto_20160709_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
