# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_client_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='alpha_label',
        ),
        migrations.RemoveField(
            model_name='client',
            name='alpha_lastupdate',
        ),
        migrations.RemoveField(
            model_name='client',
            name='beta_label',
        ),
        migrations.RemoveField(
            model_name='client',
            name='beta_lastupdate',
        ),
        migrations.RemoveField(
            model_name='client',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='domain_prefix',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(default='Default Company', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='prefs_color_accent',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='prefs_color_bg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='prefs_color_sidebar',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
