# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_auto_20160803_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='./img/logos/'),
        ),
    ]
