load:
  prefix  : ""
  suffix  : ".csv"
  mds     :
    - filename  : "test_file"
      type      : "csv"
      etl       : "none"
      desc      : "For diversity testing"
match:
  type    : "cluster"
  distance:
    f       : "binary_diff"
    cols    : ""
  params:
    method    : ""
    k_size    : 10
    num_swaps : 100
    maximize  : 0
evaluate:
  diversity   :
    - class
display :
  type  : "cluster"
save:
  prefix  : ""
  suffix  : ".csv"
  results :
    - varname   : "display_results"
      filename  : "test_results"
      type      : "csv"
grid:
  algos :
    - greedy_adaptive
  n : 
    - 100
    - 500
    - 1000
  m :
    - 2 
    - 3
  k :
    - 5
    - 10
  iter : 10
        
