load:
  mds     :
    - filename  : "data/mini.csv"
      type      : "csv"
      etl       : "none"
      desc      : "Mini data set"
match:
  type    : "cluster"
  distance:
    f       : "d_exp_neg_l2_norm"
    cols    :
      - "var1"
      - "var2"
      - "var3"
      - "var4"
  params:
    method    : "adapt"
    k_size    : 2
    f_gom     : "cluster_mean_distance"
display :
  type  : "cluster"
save:
  results :
    - varname   : "display_results"
      filename  : "data/mini_results.csv"
      type      : "csv"