# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_hstore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('welcome', '0002_auto_20160709_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('params', django_hstore.fields.DictionaryField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('run_start', models.DateTimeField()),
                ('run_end', models.DateTimeField()),
                ('output', django_hstore.fields.DictionaryField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome.Client')),
            ],
        ),
    ]
