# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_result_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='run_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='run_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
