# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_hstore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_auto_20160803_0227'),
        ('dataset', '0003_auto_20160803_0343'),
        ('match', '0003_auto_20160724_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('config', django_hstore.fields.DictionaryField()),
                ('run_start', models.DateTimeField(blank=True, null=True)),
                ('run_end', models.DateTimeField(blank=True, null=True)),
                ('result', django_hstore.fields.DictionaryField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome.Client')),
                ('data_tables', models.ManyToManyField(to='dataset.DataTable')),
            ],
        ),
        migrations.RemoveField(
            model_name='config',
            name='client',
        ),
        migrations.RemoveField(
            model_name='result',
            name='client',
        ),
        migrations.RemoveField(
            model_name='result',
            name='config',
        ),
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
