# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 18:53
from __future__ import unicode_literals

from django.db import migrations
import django_hstore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20160803_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='result',
            field=django_hstore.fields.SerializedDictionaryField(),
        ),
    ]
