# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_auto_20160819_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='data_tables',
            field=models.ManyToManyField(related_name='matches', to='dataset.DataTable'),
        ),
    ]
